"""Public surface of the shared common package."""

from .config import (
    CAPITALS_FILE,
    DATA_DIR,
    DATASET_FILE,
    DEFAULT_CONFIG,
    DELTA,
    GAMMA,
    METADATA_FILE,
    MIN_SEGMENT_SHARE,
    NON_LINEARITY_THRESHOLD,
    OUTPUT_DIR,
    PREFERENCES_DIR,
    PREFERENCES_FILE,
    PROCESSED_DIR,
    PROJECT_ROOT,
    RAW_DIR,
    SELECTED_SUBSET_FILE,
    WEIGHT_LB,
    WEIGHT_UB,
    UtaConfig,
)
from .data_loading import load_data, load_preferences, load_removal_indices
from .exceptions import (
    DataLayerError,
    InconsistentDataError,
    MissingDataError,
    SolverError,
)
from .logging_utils import get_logger
from .uta_core import (
    add_anti_flatness_constraints,
    add_monotonicity_constraints,
    add_normalization_constraints,
    add_weight_bound_constraints,
    compute_characteristic_points,
    compute_utility,
    create_marginal_value_variables,
    interpolate_value,
    solve_model,
)

__all__ = [
    "CAPITALS_FILE",
    "DATA_DIR",
    "DATASET_FILE",
    "DEFAULT_CONFIG",
    "DELTA",
    "DataLayerError",
    "GAMMA",
    "InconsistentDataError",
    "METADATA_FILE",
    "MIN_SEGMENT_SHARE",
    "MissingDataError",
    "NON_LINEARITY_THRESHOLD",
    "OUTPUT_DIR",
    "PREFERENCES_DIR",
    "PREFERENCES_FILE",
    "PROCESSED_DIR",
    "PROJECT_ROOT",
    "RAW_DIR",
    "SELECTED_SUBSET_FILE",
    "SolverError",
    "UtaConfig",
    "WEIGHT_LB",
    "WEIGHT_UB",
    "add_anti_flatness_constraints",
    "add_monotonicity_constraints",
    "add_normalization_constraints",
    "add_weight_bound_constraints",
    "compute_characteristic_points",
    "compute_utility",
    "create_marginal_value_variables",
    "get_logger",
    "interpolate_value",
    "load_data",
    "load_preferences",
    "load_removal_indices",
    "solve_model",
]
